### ISSUE TITLE
Plugin distribution?

### ISSUE THREAD

**Issue by ashald** [poseidon/terraform-provider-ct#51]
Hi there,

please let me know if you're comfortable with the plugin being distributed via [`para` Terraform community plugin manager](https://github.com/paraterraform/para) as `ct` - https://github.com/paraterraform/index/commit/54a6ea4cad6ab513dbaa4d23faf7961beaef4aac.

If no - I'd remove it from index immediately.

If yes - please feel free to submit patches to the default index referenced above when you release a new version. Alternatively, you can maintain your own feed of releases in your repo using [index extensions](https://github.com/paraterraform/para#extensions) with [relevant instructions](https://github.com/ashald/terraform-provider-stateful/commit/8af14a6a52fe4cb10ee59eb9c4f4d837943618e3) as seen in [`terraform-provider-stateful`](https://github.com/ashald/terraform-provider-stateful/blob/master/provider.stateful.yaml).

All the best!

**Comment by dghubble** [comment]
Hey Borys, the source code is freely available to anyone who wishes to build themselves or distribute plugin binaries (see the license).

However, I plan to continue providing signed, pre-compiled binaries as official [releases](https://github.com/poseidon/terraform-provider-ct/releases) as usual. Rather than openning PRs to other folks' repos to release my software. I'm not really keen on an abstraction layer here. But best of luck on your project!
